
#Problem Set 1: Answers and Analysis using R
##R edit by RJ Neel
##Original Author: Ben Lambert

###Getting started with R
R is a free programming language used for statistical analysis (and much more). Other softwares used for statistical analysis are Gretl, IBM SPSS, MATLAB, Python and many more. Python is the leading data analysis language. R is popular among academics.

The following link covers all the necessary information regarding R and R studio installation
Link:https://www.youtube.com/watch?v=9-RrkJQQYqY

###The Crime-Unemployment data set

Let's begin by 
```{r}
#Crime Unemployment data analysis

#Read
data=read.csv(file="D:/RWorks/Econometrics2/Datasets/problemset1.csv")
head(data)

# Visualize
library(ggplot2)

#Scatterplot
ggplot(data=data,aes(x=data$Unemployment,y=data$Violence,col=data$State))+geom_point()+xlab('Unemployment')+ylab('Violence')+ggtitle("Scatterplot: Unemployment vs Violence, States, 2010")

ggplot(data=data,aes(x=data$Unemployment,y=data$Violence)),labels=rownames(data$State))+geom_point()+xlab('Unemployment')+ylab('Violence')+ggtitle("Scatterplot: Unemployment vs Violence, States, 2010")+geom_text()

#Boxplot
ggplot(data=data,aes(x=data$Unemployment,y=data$Violence))+xlab('Unemployment')+ylab('Violence')+ggtitle("Boxplot: Unemployment vs Violence, States, 2010")+geom_boxplot(outlier.colour="red", outlier.shape=25,outlier.size=6, notch=FALSE)

boxplot(data$Unemployment)
boxplot(data$Violence)

#Density plot
library(e1071)
par(mfrow=c(1, 2))  # divide graph area in 2 columns
plot(density(data$Unemployment), main="Density Plot: Unemployment", ylab="Frequency", sub=paste("Skewness:", round(e1071::skewness(data$Unemployment), 2)))  # density plot for 'Unemployment'
polygon(density(data$Unemployment), col="pink")

plot(density(data$Violence), main="Density Plot: Violence", ylab="Frequency", sub=paste("Skewness:", round(e1071::skewness(data$Violence), 2)))  # density plot for 'Violence'
polygon(density(data$Violence), col="light green")

#Histogram
hist(data$Unemployment,col='pink',main = "Histogram of Unemployment",xlab='Unemployment by States')
hist(data$Violence,col='light green',main = "Histogram of Violence",xlab = 'Violence by States')


# Simple Quantification
cor(data$Unemployment,data$Violence)
